name: FTP Deploy
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      # --- ADD THIS STEP TO FIX THE ERROR ---
      - name: Clear npm Cache
        run: npm cache clean --force
      # ------------------------------------

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js Static Site
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          remote-dir: jsbs.jameasaifiyah.edu/public_html/
          cleanup: true
